# Generated by Django 5.2.17 on 2026-08-11 05:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('PENDING', '대기'), ('APPROVED', '승인'), ('REJECTED', '반려')], default='PENDING', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('complaint_type', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('occurred_on', models.DateField()),
                ('reported_on', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('RECEIVED', '접수'), ('REVIEW', 'RA/QA 검토'), ('AE_DECISION', '이상사례 판단'), ('RISK', '위험평가'), ('CAPA_DECISION', 'CAPA 판단'), ('REPORT_REVIEW', '규제보고 검토'), ('RECALL_REVIEW', '리콜 검토'), ('APPROVAL', '관리자 승인'), ('ACTION_COMPLETE', '조치 완료'), ('CLOSED', '종료')], default='RECEIVED', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField()),
                ('preventive_action', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', '개시'), ('INVESTIGATION', '조사'), ('IMPLEMENTATION', '실행'), ('EFFECTIVENESS', '효과확인'), ('CLOSED', '종료')], default='OPEN', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='pms.customercomplaint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=pms.models.upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'txt', 'csv'])])),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pms.customercomplaint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('model_number', models.CharField(max_length=100)),
                ('risk_class', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='pms.manufacturer')),
            ],
            options={
                'unique_together': {('manufacturer', 'model_number')},
            },
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='pms.medicaldevice'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('level', models.CharField(default='INFO', max_length=10)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientAnonymousInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anonymous_code', models.CharField(max_length=64, unique=True)),
                ('age_band', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_info', to='pms.customercomplaint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=50)),
                ('outcome', models.CharField(max_length=100)),
                ('serious', models.BooleanField(default=False)),
                ('narrative', models.TextField()),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event', to='pms.customercomplaint')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pms.patientanonymousinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('manufactured_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('distributed_quantity', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pms.medicaldevice')),
            ],
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='pms.productlot'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STAFF', '직원'), ('RA_QA', 'RA/QA'), ('ADMIN', '관리자')], default='STAFF', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('risk_level', models.CharField(max_length=10)),
                ('distributed_quantity', models.PositiveIntegerField()),
                ('target_quantity', models.PositiveIntegerField()),
                ('recovered_quantity', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('approval_status', models.CharField(choices=[('DRAFT', '작성'), ('PENDING', '승인대기'), ('APPROVED', '승인'), ('REJECTED', '반려')], default='DRAFT', max_length=10)),
                ('progress_status', models.CharField(choices=[('PLANNED', '계획'), ('ACTIVE', '진행'), ('COMPLETED', '완료'), ('CLOSED', '종료')], default='PLANNED', max_length=10)),
                ('closure_report', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recalls', to='pms.medicaldevice')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecallTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('target_quantity', models.PositiveIntegerField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pms.productlot')),
                ('recall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='pms.recall')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegulatoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(max_length=50, unique=True)),
                ('required', models.BooleanField(default=False)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('investigation_result', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', '작성'), ('REVIEW', '검토'), ('APPROVED', '승인'), ('SUBMITTED', '제출'), ('REJECTED', '반려')], default='DRAFT', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_reports', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='pms.customercomplaint')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('probability', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('level', models.CharField(editable=False, max_length=10)),
                ('capa_review_required', models.BooleanField(default=False, editable=False)),
                ('rationale', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='pms.customercomplaint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_identifier', models.CharField(max_length=100, unique=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udis', to='pms.medicaldevice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productlot',
            name='udi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='pms.udi'),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='udi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pms.udi'),
        ),
        migrations.AlterUniqueTogether(
            name='productlot',
            unique_together={('udi', 'lot_number', 'serial_number')},
        ),
    ]
