# Generated by Django 5.2.17 on 2026-08-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_approval_snapshot_recall_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='recall',
            name='decision_reason',
            field=models.TextField(blank=True),
        ),
    ]
