from django.urls import include, path
from rest_framework.routers import DefaultRouter
from . import api, views

r=DefaultRouter()
for prefix,view,base in [("manufacturers",api.ManufacturerViewSet,"manufacturer"),("devices",api.DeviceViewSet,"device"),("udis",api.UDIViewSet,"udi"),("lots",api.LotViewSet,"lot"),("complaints",api.ComplaintViewSet,"complaint"),("adverse-events",api.AdverseEventViewSet,"adverse"),("risks",api.RiskViewSet,"risk"),("capas",api.CAPAViewSet,"capa"),("recalls",api.RecallViewSet,"recall"),("reports",api.ReportViewSet,"report"),("approvals",api.ApprovalViewSet,"approval"),("notifications",api.NotificationViewSet,"notification"),("audits",api.AuditViewSet,"audit")]: r.register(prefix,view,basename=base)

urlpatterns=[
 path("",views.dashboard,name="dashboard"),path("complaints/",views.complaint_list,name="complaint-list"),path("complaints/new/",views.complaint_create,name="complaint-create"),path("complaints/<int:pk>/",views.complaint_detail,name="complaint-workspace"),
 path("complaints/<int:pk>/transition/",views.complaint_transition,name="complaint-transition"),path("complaints/<int:pk>/risk/",views.risk_save,name="risk-save"),path("complaints/<int:pk>/capa/",views.capa_create,name="capa-create"),path("complaints/<int:pk>/report/",views.report_create,name="report-create"),path("complaints/<int:pk>/recall/",views.recall_create,name="recall-create"),path("complaints/<int:pk>/approval/request/",views.approval_request,name="approval-request"),path("complaints/<int:pk>/approval/<int:approval_pk>/decide/",views.approval_decide,name="approval-decide"),path("complaints/<int:pk>/attachments/",views.attachment_upload,name="attachment-upload"),
 path("devices/",views.device_list,name="device-list"),path("lots/",views.lot_list,name="lot-list"),path("adverse-events/",views.adverse_list,name="adverse-list"),path("capas/",views.capa_list,name="capa-list"),path("recalls/",views.recall_list,name="recall-list"),path("reports/",views.report_list,name="report-list"),path("reports/<int:pk>/print/",views.report_print,name="report-print"),path("approvals/",views.approvals,name="approval-list"),path("notifications/",views.notifications,name="notifications"),path("audits/",views.audit_logs,name="audit-list"),path("users/",views.users,name="user-list"),path("attachments/<int:pk>/download/",views.attachment_download,name="attachment-download"),path("api/",include(r.urls)),
]
